# Programming Assignment - Longest Palindrome
# For this assignment, you have to write a complete Python program.

# You may define additional auxiliary functions as needed.
# There are some public test cases and some (hidden) private test cases.
# "Compile and run" will evaluate your submission against the public test cases
# "Submit" will evaluate your submission against the hidden private test cases. There are 10 private test cases, with equal weightage. You will get feedback about which private test cases pass or fail, though you cannot see the actual test cases.
# Ignore warnings about "Presentation errors".

# Find the longest palindrome
# (IARCS OPC Archive, K Narayan Kumar, CMI)

# As we all know, a palindrome is a word that equals its reverse. Here are some examples of palindromes: malayalam, gag, appa, amma.

# We consider any sequence consisting of the letters of the English alphabet to be a word. So axxb,abbba and bbbccddx are words for our purpose. And aaabbaaa, abbba and bbb are examples of palindromes.

# By a subword of a word, we mean a contiguous subsequence of the word. For example the subwords of the word abbba are a, b, ab, bb, ba, abb, bbb, bba, abbb, bbba and abbba.

# In this task you will given a word and you must find the longest subword of this word that is also a palindrome.

# For example if the given word is abbba then the answer is abbba. If the given word is abcbcabbacba then the answer is bcabbacb.

# Solution hint
# Any subword of w that is a palindrome is also a subword when w is reversed.

# Input format
# The first line of the input contains a single integer N indicating the length of the word. The following line contains a single word of length N, made up of the letters a,b,…, z.

# Output format
# The first line of the output must contain a single integer indicating the length of the longest subword of the given word that is a palindrome. The second line must contain a subword that is a palindrome and which of maximum length. If there is more than one subword palindrome of maximum length, print the one that is lexicographically smallest (i.e., smallest in dictionary order).

# Test Data:
# You may assume that 1 ≤ N ≤ 5000. You may further assume that in 30% of the inputs 1 ≤ N ≤ 300.

# Example:
# We illustrate the input and output format using the above examples:

# Sample Input 1:
# 5
# abbba
# Sample Output 1:
# 5
# abbba
# Sample Input 2:
# 12
# abcbcabbacba
# Sample Output 2:
# 8
# bcabbacb

# Sample Test Cases

# Input	Output
# Test Case 1	
# 12
# abcbcabbacba
# Test Case 2	
# 50
# tnautwzhfcsqesmrayxqknytkktynkqxyarmseqscfhzwtuant
# Test Case 3	
# 280
# ofntcsgzvdfzqlvuipipydmzpsgvdwxrdmlfetebwjdowylgotvowhnlavifrhwwuhbadhczqhqofbwvwrmubbhdxpiqwensoottwxuoekflnbjjvvdywkbtblkyrzqhnlalkvcqfjcvklehikfewiayvkynjquyevmoomveyuqjnykvyaiqqhxzjslwztglakjjkhgwhthaoieluudmbalmvwiwrqhsbqdnajmjdvjtdpgzkjlllwyiviemznecejrgtdrybbteqbgakroxqmgl
# 30
# iayvkynjquyevmoomveyuqjnykvyai
# Test Case 4	
# 800
# tfbkfefsghlrnpiqurtxisosaizbhnkcsmpxquszcfsrvahprcpbvdtxlvyuilzaxoapisqmzjdujnmdrbemgaktvkodvpfudfmnzcablfvxujcmkgaqimmdxaiuporuvdhxfjytpvqlfuxpaailmuqlwzgnpxhkcohjyhcpducioczrchcodsaztioihvtjkcskkxbprfxihwzjgdylxalribzrxuajxuvjryaldzvlxuudzupwucpedpvclxlkugvnevykutvsprxqmopiqepwvmahmmrguntbiulfpixhzuxljmwbtlzoxavjoprkcllmfyrwgqdgnbtwppziabzadultldltludazbaizppwtbngdqgwryfmllckrpojvaxozltbwmjlxuzhdnorcvpvtymxgzazxppyarzzrevdxhgbwwsytjumjijphlpedgedxeerkzwigcjfaddtozhahtpoeguhozmofqfpsbzafkffpjaeijescvgjedssefglxlcpocstmxaeicitmolqltzpwuiabonycqqquimghmkqpujdkutypvnmpxoqocqqugioquwyjhqadbdqxwomtdyibpyptphnxrbqmxqxggxmjacgysssvtayibpbswqrqrhcqxbxfyloynwyhpqeitfswuvotlhjepnuoorwmcmmrjkaydfiymcugxkzkrkoixixncvzghnyqaaqfhydtcxazjblaozlnikbmfcsmqsfstvxawawyzyaiblkpnxdxhgjoibbauispfrrbtncslccnppe
# 101
# hzuxljmwbtlzoxavjoprkcllmfyrwgqdgnbtwppziabzadultldltludazbaizppwtbngdqgwryfmllckrpojvaxozltbwmjlxuzh
# Test Case 5	
# 1500
# hiuuedvipfzkkreondlpchyzwvoyvblclfyriuzabakorrcgunywwyyutouopfqckrttnuvqufeoyiwtvurttromfkdwqvyamtvznqqkyuyydwratlwmcmakwdgmzhpnckpqdfadbabgyvjrghfktiupndemmtcofrgkyipzktijotcwaigtsdkfiosujwkrnrdlztmkmuvcpxyphgizjtfrjznvvymkrrvqmjcygxcvxalgjtiuonoaobvlbjxsasjnbnnhnqdksqsdjayapmafnxqpgnjihuxlinuvdzhxpzbbczbrldxacpridbsmvqzffuaivjhnlkonlreywbzyrsiwvakrskwzgzhdirqtdggpxnnvqothhdfcgqvacuakvjnfagzemhtkwihnxbwgeckkuilyclizwxexdddsnyelglyfovltzyftgstkfdjcanbgteyicctkpsqepdzobejhzctgfckhqlpjrnrvrmghgynvbmlfquoryiydkkncwcnnsgljtrszrfxuribkfqddadjkowpkyczsjkcedwfwecrxnshsklxkqgxeemqfqqxbcbhiyneerxbgsjacwypmgmtnajsszrwetdmtssxkqyskjtmftbubpnoryimaaietlsmeklqcjkmtdzaycuaujqnizzkbhouvgizstrvedhxhiyhnujjgcwqdwaefoaawibodslhwtffdfoqzyzhcyxfuxjznjcjtdawyldwgkbkrrcrreatcyyyvhzlqbujfwhdinzqzccrvfknjkgliflgokrhonstkayupzkodnfyupldcuqkbbspnjybxrwjtwdivpwaeczytmdvgtijwazmmxplqmujizrgqogvsftnuzlauvkrvlfjkuubiqmrpexgufdonwdhxqjslvljgqstknwtfkmvoldkqgadegmcwwuirfravlvharcgbqbsbgeumhzqnmslkotbtmdqyyayreevvhnyntubcusrimdsbyvwlzplxplptskozzppujqxdkonztfcsdyfcnqzedqyvcovddmypcxupniohpqbsogueywkbmkxrzuuegutktobhypqnfrgwxccvymynxvgypaexxakqqlzobpbigjgfoicmxbbwyhuokanjazzqlzeooiwxtdehnhwkixgghcwtdmcfldwyccmtmlqgqunddlqnlywsbsnggplssjsxmfqasigiewnkhfxsetmfoznuqaolkhiyoaygkfqqdfaklyfpttwhvlcllsyvzitpisxuznlevnoonvelnzuxsiptizvysllclvhwttpfylkafdqqfkgyaoyihkloaqunzofmtesxfhknweigisaqfmxsjsslpggnsbswylnqlddnuqggnvxhpvomgsxrlwpmgiepcbldrwhmmyuzvrgmoxyurwneuctanxrryfvpbebpcvpyoxkcwjyohmsdolfdizvjeqyhwcxzzozollsi
# 200
# gqunddlqnlywsbsnggplssjsxmfqasigiewnkhfxsetmfoznuqaolkhiyoaygkfqqdfaklyfpttwhvlcllsyvzitpisxuznlevnoonvelnzuxsiptizvysllclvhwttpfylkafdqqfkgyaoyihkloaqunzofmtesxfhknweigisaqfmxsjsslpggnsbswylnqlddnuqg
# Test Case 6	
# 2000
# jnrofbluttxmxhgesbyjhhwdkmyppnhybapgeacxwblvjrbbvzmcjkitygkptspwueeyhjvfkhavacyxbkamwkfuqqjlkbkefodoxatkjwfkyehbqjqnvvhlntzxujebzhqzjjjthodhumjlyzytwhhkcihwtlasuqtebcxjtcqpqbaqcakzitlkbujuijocziicmhnhlexehxukyglizyscsdwamnfnxpsjxfrklqotnjfnpsvrqqtktslifsxehpngvgtgwhbmsgzkaxbspwdioosviqzrfpyaxrjwakittjftiioxerivhaspqugylgaizjeawovraamiiagorqlyqepjywjjejtevaerobkqbwzlxhbqxnppreyrchchtvlovrhmsrcvndgmgdnvcrsmhrvolvthchcryerppnxqbhxlzwbqkboreavetjejjwyjpeqylqrogaiimaarvowaejziaglyguqpsahvirexoiitfjttikawjrxaypfrzqivsooidwpsbxakzgsmbhwgtgvgnphexsfilstktqqrvspnfjntoqlkrfxjspxnfnmawdscsyzilgykuxhexelhkjdjwszpyzidjkkcixsfozrgqwbfzjsmsvvrpwgnypqhbcljzdppcixseazgjrsempvdodtmujtwoehnjwflfcflderoylumbpqrvjdpuynievyntdyyhfmklfbjrvwunmlivqzropaskahdfhemmqzxxahovfiirvsolufbjhvtjcyolcbxuaxsagixltieoaucubddlzyudxjpbmoyolqqtangtvkiyemsipytqynuvwjxkzxylnogpcnjzztxefsmuqflouhmtqldpiecxslmwyxyxqvdvnrsfydwtmkmevrvfvycqlqojomiekoczfufgzdblnppkgkpektuvjkgzxrehfigmcnsbqtofifrrpgvczrzlbikazqhgyqsadndwitdtyvkqbhudatqddaectnkrdfujszhatkttffjjmdoozescgwhzlrrrwnaqmhrhtmbbukmiqaxpgprmnymysfpqsrheaaouopxibjrrlqgrfaduaruuwmlqdsxgslcgazrbiittybmfdpbejvyfhlwndttxgveguvjefezfglmlcnrlistsdrfhmyesvkarhjvoowtwjhhluzzfruxuncdzcktzutqcelssjmqstyfqzgvsauonyuoaejzyercjevdnjufeumwttrntnbjlvznbjoanfeyjbcwmwdrsqnllhaeudpibpvcakeppjozmsxzodqivfvgovmlyctztocvagkqraresqditvqoclurijehlxignmdovngmqzsipxtlujbxxyqfhuoutxcglfwgsevkdptvnmihxjgwjwcqssmlroudtsloziyeytbnhjwfvddebhxuajhradwtyijxsibqbddjoaqlfvqgdpcdakwcpvwpdhmxpqotvtejtwxarphwejzgvyjnthcyorvghlzcffnabmbubkrftsorsxelgiluzjagubkzgacjmfgqpxvkrlbkkhxqqjlrsnaorkqxmsjbxproooyhacrkjrdbcqtwdvkufauuufvtwohmcgteinrteuxgkscpnomuriolnlhjbovewqkgdbajxzpjrtzgklabtroievtgkqmggwpmarvxqnhjiipsvrtqkkypftxrjjyrhpdhgbhwoqfyywrtpmjawjrecovnzvegkkqqlxmbntbnrsghhrjfacjesfrravznhpdumqvblzodrwmanxgpbrttymmbklordrmpjjtvihaceoctnkjocejcrxdbkrunlgfusyrchtelhjhwvqkzwvcnufqfzluktzenzwqhrwuzhbvdticqfefamwhljbvedbsczklrggsqjptdxxvfeahqyodjpaosbixbsisaqmqcbjfbhcglcndddgmsganjimmcwgdpsvruhyvq
# 401
# hlexehxukyglizyscsdwamnfnxpsjxfrklqotnjfnpsvrqqtktslifsxehpngvgtgwhbmsgzkaxbspwdioosviqzrfpyaxrjwakittjftiioxerivhaspqugylgaizjeawovraamiiagorqlyqepjywjjejtevaerobkqbwzlxhbqxnppreyrchchtvlovrhmsrcvndgmgdnvcrsmhrvolvthchcryerppnxqbhxlzwbqkboreavetjejjwyjpeqylqrogaiimaarvowaejziaglyguqpsahvirexoiitfjttikawjrxaypfrzqivsooidwpsbxakzgsmbhwgtgvgnphexsfilstktqqrvspnfjntoqlkrfxjspxnfnmawdscsyzilgykuxhexelh
# Test Case 7	
# 1000
# qfqnvhtczmegaalgozmlgvbkvxvjbisupjhmsbotpuzrxmxlnlytjaggzbpblkxcteonhegyafpxtokgcjallgtkjinwskynroaasgzunqsihcpjnrwazplkzagslehesiemqfggwaofffouymvxbihaiputtcznmebcjikhkzmpgckfofernosxdotzqsmewqhiytpkseabgkixrmogcidgzwfprtunjdxjwnurtusbgcyzopfrzkzyjeoazkpjpnuncogvkawscxrtoyknjlmupcuqojzfwwsykzvxbupetjxhhjusugmligbysddozwplxmkaiaebldisodnilzvwixuacyqdwhqvwbvedagofoguttcfvabdxvfbvxerfwmbxifaknqpczjvuoapodunzzowxuoeqahqkoqucjmeivbcjeszhomiocfnwttpvafiqxcsgqyomatxelznzlwpobemwzdtbibsigkqwlhklairljgmucekfkzbkcvlnydveqnbbulouvhhenubsanxkmbupyiewlzbddbzlweiypubmkxnasbunehhvuolubbnqevdynlvckbzkfkecumgjlrialkhlwqkgisbibtdzwmebopwlznzlextamoyqgscxqifavpttwnfcoimohzsejcbviemjcuqokqhaqeouxwozznudopaouvjzcpqnkafixbmwfrexvbfvxdbavfcttugofogadevbwvqhwdqycauxiwvzlindosidlbeaiakmxlpwzoddsybgilmgusujhhxjteoegjrudpdlvthwlhkkrylonjwrijsjnhpvqisvxvgvontbwdmoexetjalrjfcyotugboczjkwaapbwvnmznqswsfpclrcbkyinmmowwkyyabxvpluecmausryfidgubqhocwmbgkbilydckxgomikgblnjotfpmpdqnrtvdvepvhthhcvvmibotozhjhwxwcojthexeko
# 500
# etjxhhjusugmligbysddozwplxmkaiaebldisodnilzvwixuacyqdwhqvwbvedagofoguttcfvabdxvfbvxerfwmbxifaknqpczjvuoapodunzzowxuoeqahqkoqucjmeivbcjeszhomiocfnwttpvafiqxcsgqyomatxelznzlwpobemwzdtbibsigkqwlhklairljgmucekfkzbkcvlnydveqnbbulouvhhenubsanxkmbupyiewlzbddbzlweiypubmkxnasbunehhvuolubbnqevdynlvckbzkfkecumgjlrialkhlwqkgisbibtdzwmebopwlznzlextamoyqgscxqifavpttwnfcoimohzsejcbviemjcuqokqhaqeouxwozznudopaouvjzcpqnkafixbmwfrexvbfvxdbavfcttugofogadevbwvqhwdqycauxiwvzlindosidlbeaiakmxlpwzoddsybgilmgusujhhxjte
# Test Case 8	
# 4500
# rnnovornotoqxerkxoirodqnbtrrdfswsilpwcdkxtauxtfuipnysdmvwdmbkhacpnsnrvxoozjotqidhwbbbpzyslbcubhlobyfwxwmxhaszlvgjyhkoikiwmnqpucevcltchhbqktpxqxgohsepdnlpccewgktkyomhvnyfincylkpsdvjgivxkzdifodrorevpttucjzcwltqopzwzuvkvzuapyudryygtudxdeabptrgksekpawkzqnqqhtihtoanrysvatnvmtgfzsuzogagtqxalhhfviupipmiizfxuleudavtgwaaoxccgkjbufseufmfgrcbfixkiseoqeqhdtjjdumzzhdumrzskdvrlsctngjdmckrvvaarozrvenjvoehrzzeubzhjkkxmxohuqhmeifcmsljgprzrsflveseoedddrkyjumperrtlfctwvsnpzykfsqvztycmjcvfoljhecslhliefvuewejqxfpqdudowatnlfusjndqylxgjrkhxuzubplelqvhsqwgvryfgdxgpumanxjltihuzuakmvufmqlhjjopmowdkifyholcxuwwpxhbsdigtttgidsbhxpwwuxclohyfikdwompojjhlqmfuvmkauzuhitljxnamupgxdgfyrvgwqshvqlelpbuzuxhkrjgxlyqdnjsuflntawodudqpfxqjeweuvfeilhlscehjlofvcjmcytzvqsfkyzpnsvwtcfltrrepmujykrdddeoesevlfsrzrpgjlsmcfiemhquhoxmxkkjhzbuezzrheovjnevrzoraavvrkcmdjgntcslrvdkszrmudhzzmudjjtdhqeqoesikxifbcrgfmfuesfubjkgccxoaawgtvadueluxfziimpipuivfhhlaxqtgagozuszfgtmvntavsyrnaothithqqnqzkwapkeskgrtpbaedxdutgyyrduypauzvkvuzwzpoqtlwczjcuttpverordofidzkxvigjvdspklycnifynvhmoyktkgweccplndpeshogxqxptkqbhhctlcvecupqnmwikiokhyjgvlzsahxmwxwfqdeesruqwfbcfkqsnpojmdivhdypjtlzwpgricjfjkjqvzkkrztfeeanjafstqusfcloguvqheicftowsjbwndkwdrrzhnrorcexyzpffyjlrxhlhlhuottsmmrtzkksoormqhuvhdgybqjkbsepozjancwomggcwypmhjkooqopixzjrgbhhkivngjbmsekqvxzghnwzboiantrvubfhjcwrnxdfdnxamwivjfvmvfokyigvjncupylcxqkdfhfseqnpxkespscqakljxndonotmedrkkxeontgkekeveglfrwqqlufakynrbedndhesckegwieapphioaybwfegdtzgzcudlyxokcwgkaibssjiskloprwvkwbmaxpovmchoanbdycxsmhmwuanmyiywkkxjbnhoroerehwcktwyciwxkjjisjfeuepvrwlklsbpzytltpjwzhtjretlnarjggfzdqjqilfklavgpfcqoxbfdustxlcdujdxampkzuumuqtlxxblvetayntvzybthesjshuudqgxibkhzntwrowrbsncqovzupjowfizvpygsknrxinqymicexeuncthrevqjerhvsnncchaluqlganmxsgkwcrnipfsvxzspohrqotdlmrrmeekymuuqoizdptamusdizxaqqgbexurbadanzwfnggswzsitmoboleebkfijzzmaeopdlutrbnnciywumzixdmaptiatjntpbktoeoghbvmjvigjhqgndjeytfrfumuxwnmddumfryqniwwsnfhsqlqjskomyjkvywacsojjnzwxyvpnawhqkzbcjqpibbfzzhdrvmaioziouxbwwiogjpkvhbdickkbrnumcxxswfgsejqatgicvtxfucpzozafpxututlsatmecchxirzfkzmhbcgqbixsftlbmytmrfrvjastruzetnlwprotboljhzkuxegplzkvbfotzpxudkqudhnevbncaayxgfmrgzmieddfuczzmpuryjxtmnymnwktdykmzzufezkablapbwibffvusvgfrsaxtnjuofasemshyuybqgcylzsgwalotonobyipfkjlxdsxysaqyeojgircjfsctfswdalklwvkznjzfjqfnervniyynqcgwucbupmhlhrnxcmelckbjbwyluwzlafjukmqbaypkrchuqnfvxigahembcnocuzyeooiomxyebharvhouquxxalacyrgssgzgvhvjevphdpyaxnunjtmkeooefxzydyeafbklxzsapsamhwbrspdydrdlqclucpwjtguqgosxgulosohkdklidqtuugqwwmfrtbhbpbavvllnbsageloibkevqutogyfbzoeopglkrxauraawnpgqbklrgggoensfcwvtdgewfgrzitxvkdllpydveljkabrcamyfuedckubsqynadamsyrpecyqcchhevhjplotvjupbuebxenpeegkihanjjwpedavooplzjaagecdkrvqybaiicvtltkrwkmmzbxanzbtffwrythyvhhflezwyjnuwcjxdixqialphihibogyynejufisqxomzxjfijxqjjhrrobufhvdxzorgyjwyzjzzuehdcxnlggevhaaqvfnwvecupbspmtogyvkcuzpahtxqvzgteupaauwsvqjhjznhwzjsaauhtsxrrgkyczyevuwqkfztgpdcoourppykhybaglyinymiulbesaazpfbgtwzinztwxwwfixnxvchqniwhjygadiixghhtjcriznojmdgifpauyycjxilcswbadjvonmxmclxoofyuvaqtzseydpavleyrptfcgcrinoycuxyrxomyjqwofzlrdjksdpwjsntherlaqjroadmltlzakktpudjztfknvduzwgznrsbtvpeqafsmqmbmpmlkuvxpauqwcpjvhmpecvwebortauhsjscdpcupyknabxvklmqpimwlangdjnxuhzzwdtnbfadgzbqnngcxuykxnsazfxtoyvmeozhucladotqdbtdwtnthgvinudcsyqypqgjutlxhgokijnecdxlluvyozciztholnxfgleprsbzbrfeuerfynfmmkvnfecsrbzzmdqgwrhzinfetxlumtgafdnmjpearfbfirlglvgvinadklxwggyllmxvbbxugzcrsnxdifzstbwfovevbcgnqekuhhoqgqhbgggqofjjihqxeusgzyvpehjmoaexsnyytepjmasujlrpflvgksyobjcqjgpetncpttahvveggvwnjtutoujpdofpuwtqjxhfrhoocsvkqryzkusyodotrviosdgdbnkuwzkbrflhyjgjdajtgznxxxnpbtueifafgmizsthqfpbksneymtxjqlatevxnczukmcjgxsyckcncptcdoznempytmxiozcalgktdcrgmtvqkquoewbiiqiddilthpwuvgnzkghzacrmumayidisutwzbhukxqesytrlzakbcbowpowxshqoampdvjnsctnamglnhxpjbdiqtgolngzpuqupahiecxeodsckptwqwgjpmxdcfetzvooxvybyxhobzslrljjjpszeregyizxfpocnodnmlbpmwcfhmprbjsfdwnbgpbmerorhsevfiktenzlbqeezwkeuzgbojntabmjvrfcbrwfgxshnxmmtytoxzrmkehmhvvfoajpshuyenirkugfszvramfksmwckrhyuqooyimexuwjqeridmadbfpvulxeegcaxsoxbbdaxzkodbyipalsicocpliusmurfjqimtilvuzyvajnawfiztmohukzjfsoqiwedgpybrzyriltetedmqstncuwjmmbwifaqxyroxqhhdamweplxjgkobizpuboeioufomtoecvhfhgjzrgixsyyayquzeajuvpkjkannwwsfcdgtmrreprhnjbopeylzpwizyxowticwmkpybietclglpxbtxmsmkcnjzcfskjqwuiwvqbosmxedwhwttqhgsuprwumjgcfakexdfoxtndzjkvegmlmghbagxmpdqufdadgfrdbejaptxvblgnspqsvqgkvyhbbhehnxnqdwsurpptbxivmbpirxsmvzpxhvgwsvoxtgrnxigyfqvsrkckhuzfwocfkkdegrebxxougwvlnsfgdhtmestcivjsimzoddrcagygcvurobatlthplbttycogonwtsovuuvbyrxshysajljaykvtjxhpnwmgqcdlwbowuloblidxtmztzvniuwzivnqlpwwnxkmrxaujlziglhamcpuxlwhijzubvsosfalcdhnogxuufwgj
# 1001
# fwxwmxhaszlvgjyhkoikiwmnqpucevcltchhbqktpxqxgohsepdnlpccewgktkyomhvnyfincylkpsdvjgivxkzdifodrorevpttucjzcwltqopzwzuvkvzuapyudryygtudxdeabptrgksekpawkzqnqqhtihtoanrysvatnvmtgfzsuzogagtqxalhhfviupipmiizfxuleudavtgwaaoxccgkjbufseufmfgrcbfixkiseoqeqhdtjjdumzzhdumrzskdvrlsctngjdmckrvvaarozrvenjvoehrzzeubzhjkkxmxohuqhmeifcmsljgprzrsflveseoedddrkyjumperrtlfctwvsnpzykfsqvztycmjcvfoljhecslhliefvuewejqxfpqdudowatnlfusjndqylxgjrkhxuzubplelqvhsqwgvryfgdxgpumanxjltihuzuakmvufmqlhjjopmowdkifyholcxuwwpxhbsdigtttgidsbhxpwwuxclohyfikdwompojjhlqmfuvmkauzuhitljxnamupgxdgfyrvgwqshvqlelpbuzuxhkrjgxlyqdnjsuflntawodudqpfxqjeweuvfeilhlscehjlofvcjmcytzvqsfkyzpnsvwtcfltrrepmujykrdddeoesevlfsrzrpgjlsmcfiemhquhoxmxkkjhzbuezzrheovjnevrzoraavvrkcmdjgntcslrvdkszrmudhzzmudjjtdhqeqoesikxifbcrgfmfuesfubjkgccxoaawgtvadueluxfziimpipuivfhhlaxqtgagozuszfgtmvntavsyrnaothithqqnqzkwapkeskgrtpbaedxdutgyyrduypauzvkvuzwzpoqtlwczjcuttpverordofidzkxvigjvdspklycnifynvhmoyktkgweccplndpeshogxqxptkqbhhctlcvecupqnmwikiokhyjgvlzsahxmwxwf
# Test Case 9	
# 2000
# qmiqodqunuvkyupgtubirbthqxmfjaezmosatixgesqcmhiidlsxmmgelsluspwggoizwficzaeoiowncqkocqvnkgkcygkewtfuynwaocoyqkluayjfqgubmgfmoqskjyejncjdexbxjprmpcrhinixwqjkgcvrabapgmtklwhvlzhcbakkpsjliswquthwwkmcyhnjdwepvntzndlfyuqimozjhihgutiscxcguixrwqqlubqsvjakxbthkapewxzyxbgtjdkhwdtqelkcummuohbajqghpfioiohsuuzqxuibgsfaeruuaxwkpdrhizvrqflkzmayhizncfpiymdbjzlbeeipgfiwktglhijqsldusvcshhtsjevnldcrlkpxfxjpfufzfltzgxsphljqsffdkkwvwlteketryyqgjjfrizgplqhdvnihzedvrwzbcssatkictoudnctasafppnxotcmmalncghcbrldmbzqqcltwnyofonthpfurtjtbrxckkhznhrelczhrxxwlksvbxrssanttlxgvffjowpzaoitliqzsiuwhnqanevjptpkauvoskpsyxlmfdlalhyvuoxjuusjphwpdrfveupcudqbgbdukbresoomiiyyquptnvrtpgyljonssqocufjmtzydhybzuttkomdfsbreqgyiymmsrvemufpedtdymwicknhdpajhghrfvfxobeaxlrbomfoadycomktdmcmvlfaikzwlfylqpmfetvexwhnitgnhkbcxgcfqedejbpasdhwxedwamlkftzodarcgvjzzmdlnunfzweyahudthnaanofnfhwbqvccaprwcxvadwdkqgfatfaivgwdnuegriktacpebmfeiiqbovbjcdsxjqazkgfbrpurtlvuzcyikolylmknrcnbspceyhfpybisofoninvsbitpwdcohrpzhrdfakwangubljqtyoobwjqtovhxmywtwymxhvotqjwbooytqjlbugnawkafdrhzprhocdwptibsvninofosibypfhyecpsbncrnkmlylokiyczuvltruprbfgkzaqjxsdcjbvobqiiefmbepcatkirgeundwgviaftafgqkdwdavxcwrpaccvqbwhfnfonaanhtduhayewzfnunldmzzjvgcradoztfklmawdexwhdsapbjedeqfcgxcbkhngtinhwxevtefmpqlyflwzkiaflvmcmdtkmocydaofmobrlxaeboxfvfrhghjapdhnkciwmydtdepfumevrsmmyiygqerbsfdmokttuzbyhdyztmjfucoqssnojlygptrvntpuqyyiimooserbkudbgbqducpuevfrdpwhpjsuujxouvyhlaldfmlxyspksovuakptpjvenaqnhwuiszqiltioazpwojffvgxlttnassrxbvsklwxxrhzclerhnzhkkcxrbtjtrufphtnofoynwtlcqqzbmdlrbchgcnlammctoxnppfasatcnduotciktasscbzwrvdezhinvdhqlpgzirfjjgqyyrteketlwvwkkdffsqjlhpsxgztlfzfufpjxfxpklrcdlnvejsthhscvsudlsqjihlgtkwifgpieeblzjbdmyipfcnzihyamzklfqrvzihrdpkwxauureafsgbiuxqzuushoioifphgqjabhoummuckleqtdwhkdjtgbxyzxwepakhtbxkajvsqbulqqwrxiugcxcsitughihjzomiquyfldnztnvpewdjnhycmkwwhtuqwsiljspkkabchzlvhwlktmgpabarvcgkjqwxinihrcpmrpjxbxedjcnjeyjksqomfgmbugqfjyaulkqyocoawnyuftwekgyckgknvqcokqcnwoioeazcifwzioggwpsulslegmmxsldiihmcqsegxitasomzeajfmxqhtbributgpuykvunuqdoqimrbat
# 1995
# miqodqunuvkyupgtubirbthqxmfjaezmosatixgesqcmhiidlsxmmgelsluspwggoizwficzaeoiowncqkocqvnkgkcygkewtfuynwaocoyqkluayjfqgubmgfmoqskjyejncjdexbxjprmpcrhinixwqjkgcvrabapgmtklwhvlzhcbakkpsjliswquthwwkmcyhnjdwepvntzndlfyuqimozjhihgutiscxcguixrwqqlubqsvjakxbthkapewxzyxbgtjdkhwdtqelkcummuohbajqghpfioiohsuuzqxuibgsfaeruuaxwkpdrhizvrqflkzmayhizncfpiymdbjzlbeeipgfiwktglhijqsldusvcshhtsjevnldcrlkpxfxjpfufzfltzgxsphljqsffdkkwvwlteketryyqgjjfrizgplqhdvnihzedvrwzbcssatkictoudnctasafppnxotcmmalncghcbrldmbzqqcltwnyofonthpfurtjtbrxckkhznhrelczhrxxwlksvbxrssanttlxgvffjowpzaoitliqzsiuwhnqanevjptpkauvoskpsyxlmfdlalhyvuoxjuusjphwpdrfveupcudqbgbdukbresoomiiyyquptnvrtpgyljonssqocufjmtzydhybzuttkomdfsbreqgyiymmsrvemufpedtdymwicknhdpajhghrfvfxobeaxlrbomfoadycomktdmcmvlfaikzwlfylqpmfetvexwhnitgnhkbcxgcfqedejbpasdhwxedwamlkftzodarcgvjzzmdlnunfzweyahudthnaanofnfhwbqvccaprwcxvadwdkqgfatfaivgwdnuegriktacpebmfeiiqbovbjcdsxjqazkgfbrpurtlvuzcyikolylmknrcnbspceyhfpybisofoninvsbitpwdcohrpzhrdfakwangubljqtyoobwjqtovhxmywtwymxhvotqjwbooytqjlbugnawkafdrhzprhocdwptibsvninofosibypfhyecpsbncrnkmlylokiyczuvltruprbfgkzaqjxsdcjbvobqiiefmbepcatkirgeundwgviaftafgqkdwdavxcwrpaccvqbwhfnfonaanhtduhayewzfnunldmzzjvgcradoztfklmawdexwhdsapbjedeqfcgxcbkhngtinhwxevtefmpqlyflwzkiaflvmcmdtkmocydaofmobrlxaeboxfvfrhghjapdhnkciwmydtdepfumevrsmmyiygqerbsfdmokttuzbyhdyztmjfucoqssnojlygptrvntpuqyyiimooserbkudbgbqducpuevfrdpwhpjsuujxouvyhlaldfmlxyspksovuakptpjvenaqnhwuiszqiltioazpwojffvgxlttnassrxbvsklwxxrhzclerhnzhkkcxrbtjtrufphtnofoynwtlcqqzbmdlrbchgcnlammctoxnppfasatcnduotciktasscbzwrvdezhinvdhqlpgzirfjjgqyyrteketlwvwkkdffsqjlhpsxgztlfzfufpjxfxpklrcdlnvejsthhscvsudlsqjihlgtkwifgpieeblzjbdmyipfcnzihyamzklfqrvzihrdpkwxauureafsgbiuxqzuushoioifphgqjabhoummuckleqtdwhkdjtgbxyzxwepakhtbxkajvsqbulqqwrxiugcxcsitughihjzomiquyfldnztnvpewdjnhycmkwwhtuqwsiljspkkabchzlvhwlktmgpabarvcgkjqwxinihrcpmrpjxbxedjcnjeyjksqomfgmbugqfjyaulkqyocoawnyuftwekgyckgknvqcokqcnwoioeazcifwzioggwpsulslegmmxsldiihmcqsegxitasomzeajfmxqhtbributgpuykvunuqdoqim
# Test Case 10	
# 2000
# rnnovornotoqxerkxoirodqnbtrrdfswsilpwcdkxtauxtfuipnysdmvwdmbkhacpnsnrvxoozjotqidhwbbbpzyslbcubhlobyfwxwmxhaszlvgjyhkoikiwmnqpucevcltchhbqktpxqxgohsepdnlpccewgktkyomhvnyfincylkpsdvjgivxkzdifodrorevpttucjzcwltqopzwzuvkvzuapyudryygtudxdeabptrgksekpawkzqnqqhtihtoanrysvatnvmtgfzsuzogagtqxalhhfviupipmiizfxuleudavtgwaaoxccgkjbufseufmfgrcbfixkiseoqeqhdtjjdumzzhdumrzskdvrlsctngjdmckrvvaarozrvenjvoehrzzeubzhjkkxmxohuqhmeifcmsljgprzrsflveseoedddrkyjumperrtlfctwvsnpzykfsqvztycmjcvfoljhecslhliefvuewejqxfpqdudowatnlfusjndqylxgjrkhxuzubplelqvhsqwgvryfgdxgpumanxjltihuzuakmvufmqlhjjopmowdkifyholcxuwwpxhbsdigttqdeesruqwfbcfkqsnpojmdivhdypjtlzwpgricjfjkjqvzkkrztfeeanjafstqusfcloguvqheicftowsjbwndkwdrrzhnrorcexyzpffyjlrxhlhlhuottsmmrtzkksoormqhuvhdgybqjkbsepozjancwomggcwypmhjkooqopixzjrgbhhkivngjbmsekqvxzghnwzboiantrvubfhjcwrnxdfdnxamwivjfvmvfokyigvjncupylcxqkdfhfseqnpxkespscqakljxndonotmedrkkxeontgkekeveglfrwqqlufakynrbedndhesckegwieapphioaybwfegdtzgzcudlyxokcwgkaibssjiskloprwvkwbmaxpovmchoanbdycxsmhmwuanmyiywkkxjbnhoroerehwcktwyciwxkjjisjfeuepvrwlklsbpzytltpjwzhtjretlnarjggfzdqjqilfklavgpfcqoxbfdustxxtsudfbxoqcfpgvalkfliqjqdzfggjranlterjthzwjptltyzpbslklwrvpeuefjsijjkxwicywtkcwhereorohnbjxkkwyiymnalcdujdxampkzuumuqtlxxblvetayntvzybthesjshuudqgxibkhzntwrowrbsncqovzupjowfizvpygsknrxinqymicexeuncthrevqjerhvsnncchaluqlganmxsgkwcrnipfsvxzspohrqotdlmrrmeekymuuqoizdptamusdizxaqqgbexurbadanzwfnggswzsitmoboleebkfijzzmaeopdlutrbnnciywumzixdmaptiatjntpbktoeoghbvmjvigjhqgndjeytfrfumuxwnmddumfryqniwwsnfhsqlqjskomyjkvywacsojjnzwxyvpnawhqkzbcjqpibbfzzhdrvmaioziouxbwwiogjpkvhbdickkbrnumcxxswfgsejqatgicvtxfucpzozafpxututlsatmecchxirzfkzmhbcgqbixsftlbmytmrfrvjastruzetnlwprotboljhzkuxegplzkvbfotzpxudkqudhnevbncaayxgfmrgzmieddfuczzmpuryjxtmnymnwktdykmzzufezkablapbwibffvusvgfrsaxtnjuofasemshyuybqgcylzsgwalotonobyipfkjlxdsxysaqyeojgircjfsctfswdalklwvkznjzfjqfnervniyynqcgwucbupmhlhrnxcmelckbjbwyluwzlafjukmqbaypkrchuqnfvxigahembcnocuzyeooiomxyebharvhouquxxalacyrgssgzgvhvjevphdpyaxnunjtmkeooefxzydyeafbklxzsa
# 200
# anmyiywkkxjbnhoroerehwcktwyciwxkjjisjfeuepvrwlklsbpzytltpjwzhtjretlnarjggfzdqjqilfklavgpfcqoxbfdustxxtsudfbxoqcfpgvalkfliqjqdzfggjranlterjthzwjptltyzpbslklwrvpeuefjsijjkxwicywtkcwhereorohnbjxkkwyiymna
# Test Case 11	
# 5
# abbba
# Test Case 12	
# 12
# abcbcabbacba


def lcw(w1,w2):
    m = len(w1)
    n = len(w2)
    lcw = []
    maxlen = 0
    maxpos = (m,n)
    for i in range(m+1):
        lcw.append([])
        for j in range(n+1):
            lcw[i].append(0)
    for i in range(m-1,-1,-1):
        for j in range(n-1,-1,-1):
            if w1[i] == w2[j]:
                lcw[i][j] = 1 + lcw[i+1][j+1]
                if lcw[i][j] > maxlen:
                    maxlen = lcw[i][j]
                    maxpos = (i,j)
                if lcw[i][j] == maxlen:
                    if w1[maxpos[0]:maxpos[0]+maxlen] > w1[i:i+maxlen]:
                        maxpos = (i,j)
            else:
                lcw[i][j] = 0
    return(maxlen,w1[maxpos[0]:maxpos[0]+maxlen])
num = input()
word = input().strip()
rword = ''.join(reversed(word))
(palinlen,palinpat) = lcw(word,rword)
print(palinlen)
print(palinpat)